//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Posts = new HashSet<Post>();
            this.Followings = new HashSet<Following>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Field { get; set; }
        public Nullable<int> ProfilePhoto { get; set; }
        public string Password { get; set; }
        public Nullable<int> Address { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual ICollection<Following> Followings { get; set; }
    }
}
