//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public Photo()
        {
            this.Companies = new HashSet<Company>();
            this.Posts = new HashSet<Post>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
