//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.Likes = new HashSet<Like>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Text { get; set; }
        public Nullable<int> Photo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual Photo Photo1 { get; set; }
        public virtual User User { get; set; }
    }
}
