//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Followings = new HashSet<Following>();
            this.Friends = new HashSet<Friend>();
            this.Friends1 = new HashSet<Friend>();
            this.Posts = new HashSet<Post>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ProfilePhoto { get; set; }
        public string Password { get; set; }
        public Nullable<int> Address { get; set; }
        public string email { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Following> Followings { get; set; }
        public virtual ICollection<Friend> Friends { get; set; }
        public virtual ICollection<Friend> Friends1 { get; set; }
        public virtual Like Like { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual Photo Photo1 { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
